//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PackageHead.proto
// Note: requires additional types generated from: PackageHeadEnum.proto
namespace Proto.Package
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PackageHead")]
  public partial class PackageHead : global::ProtoBuf.IExtensible
  {
    public PackageHead() {}
    
    private Proto.Package.PackageType _packageType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"packageType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Proto.Package.PackageType packageType
    {
      get { return _packageType; }
      set { _packageType = value; }
    }
    private Proto.Package.FunctionCode _functionCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"functionCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Proto.Package.FunctionCode functionCode
    {
      get { return _functionCode; }
      set { _functionCode = value; }
    }
    private string _destination;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"destination", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string destination
    {
      get { return _destination?? ""; }
      set { _destination = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool destinationSpecified
    {
      get { return this._destination != null; }
      set { if (value == (this._destination== null)) this._destination = value ? this.destination : (string)null; }
    }
    private bool ShouldSerializedestination() { return destinationSpecified; }
    private void Resetdestination() { destinationSpecified = false; }
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId?? ""; }
      set { _userId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userIdSpecified
    {
      get { return this._userId != null; }
      set { if (value == (this._userId== null)) this._userId = value ? this.userId : (string)null; }
    }
    private bool ShouldSerializeuserId() { return userIdSpecified; }
    private void ResetuserId() { userIdSpecified = false; }
    
    private string _moduleId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"moduleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string moduleId
    {
      get { return _moduleId?? ""; }
      set { _moduleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool moduleIdSpecified
    {
      get { return this._moduleId != null; }
      set { if (value == (this._moduleId== null)) this._moduleId = value ? this.moduleId : (string)null; }
    }
    private bool ShouldSerializemoduleId() { return moduleIdSpecified; }
    private void ResetmoduleId() { moduleIdSpecified = false; }
    
    private int? _messageCode;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"messageCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int messageCode
    {
      get { return _messageCode?? default(int); }
      set { _messageCode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool messageCodeSpecified
    {
      get { return this._messageCode != null; }
      set { if (value == (this._messageCode== null)) this._messageCode = value ? this.messageCode : (int?)null; }
    }
    private bool ShouldSerializemessageCode() { return messageCodeSpecified; }
    private void ResetmessageCode() { messageCodeSpecified = false; }
    
    private string _messageText;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"messageText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string messageText
    {
      get { return _messageText?? ""; }
      set { _messageText = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool messageTextSpecified
    {
      get { return this._messageText != null; }
      set { if (value == (this._messageText== null)) this._messageText = value ? this.messageText : (string)null; }
    }
    private bool ShouldSerializemessageText() { return messageTextSpecified; }
    private void ResetmessageText() { messageTextSpecified = false; }
    
    private string _customText;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"customText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string customText
    {
      get { return _customText?? ""; }
      set { _customText = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool customTextSpecified
    {
      get { return this._customText != null; }
      set { if (value == (this._customText== null)) this._customText = value ? this.customText : (string)null; }
    }
    private bool ShouldSerializecustomText() { return customTextSpecified; }
    private void ResetcustomText() { customTextSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}