# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PackageHead.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PackageHeadEnum_pb2 as PackageHeadEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PackageHead.proto',
  package='Proto.Package',
  syntax='proto2',
  serialized_options=b'\n\017com.cc.protobufB\014PackageHeads',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11PackageHead.proto\x12\rProto.Package\x1a\x15PackageHeadEnum.proto\"\xe6\x01\n\x0bPackageHead\x12/\n\x0bpackageType\x18\x01 \x02(\x0e\x32\x1a.Proto.Package.PackageType\x12\x31\n\x0c\x66unctionCode\x18\x02 \x02(\x0e\x32\x1b.Proto.Package.FunctionCode\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x0e\n\x06userId\x18\x04 \x01(\t\x12\x10\n\x08moduleId\x18\x05 \x01(\t\x12\x13\n\x0bmessageCode\x18\x06 \x01(\x05\x12\x13\n\x0bmessageText\x18\x07 \x01(\t\x12\x12\n\ncustomText\x18\x08 \x01(\tB\x1f\n\x0f\x63om.cc.protobufB\x0cPackageHeads'
  ,
  dependencies=[PackageHeadEnum__pb2.DESCRIPTOR,])




_PACKAGEHEAD = _descriptor.Descriptor(
  name='PackageHead',
  full_name='Proto.Package.PackageHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageType', full_name='Proto.Package.PackageHead.packageType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='functionCode', full_name='Proto.Package.PackageHead.functionCode', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destination', full_name='Proto.Package.PackageHead.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='Proto.Package.PackageHead.userId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='moduleId', full_name='Proto.Package.PackageHead.moduleId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageCode', full_name='Proto.Package.PackageHead.messageCode', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageText', full_name='Proto.Package.PackageHead.messageText', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customText', full_name='Proto.Package.PackageHead.customText', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=290,
)

_PACKAGEHEAD.fields_by_name['packageType'].enum_type = PackageHeadEnum__pb2._PACKAGETYPE
_PACKAGEHEAD.fields_by_name['functionCode'].enum_type = PackageHeadEnum__pb2._FUNCTIONCODE
DESCRIPTOR.message_types_by_name['PackageHead'] = _PACKAGEHEAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PackageHead = _reflection.GeneratedProtocolMessageType('PackageHead', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGEHEAD,
  '__module__' : 'PackageHead_pb2'
  # @@protoc_insertion_point(class_scope:Proto.Package.PackageHead)
  })
_sym_db.RegisterMessage(PackageHead)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
