# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoDevPricing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoDevPricing.proto',
  package='Proto.DevPricing',
  syntax='proto2',
  serialized_options=b'\n\017com.cc.protobufB\020ProtoDevPricings',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15ProtoDevPricing.proto\x12\x10Proto.DevPricing\"\xcb\x03\n\x12ProtoDevPricingReq\x12/\n\x08\x44\x65v_Type\x18\x01 \x02(\x0e\x32\x1d.Proto.DevPricing.EnumDevType\x12\x16\n\tYear_Days\x18\x02 \x02(\x05:\x03\x32\x35\x32\x12\x10\n\x08\x44uration\x18\x03 \x02(\x05\x12\x12\n\nVolatility\x18\x04 \x02(\x01\x12\x15\n\rRiskFree_Rate\x18\x05 \x02(\x01\x12\x0e\n\x06Strike\x18\x06 \x01(\x01\x12\n\n\x02S0\x18\x07 \x01(\x01\x12\n\n\x02S1\x18\x08 \x01(\x01\x12\x14\n\x0c\x45xpected_Ret\x18\t \x01(\x01\x12\x16\n\x0eKnockOut_Ratio\x18\n \x01(\x01\x12\x17\n\x0fKnockOut_Ratio2\x18\x0b \x01(\x01\x12\x15\n\rKnockIn_Ratio\x18\x0c \x01(\x01\x12\x17\n\x0fKnockOut_Return\x18\r \x01(\x01\x12\x17\n\x0fStart_Obsv_Date\x18\x0e \x01(\x05\x12\x12\n\nMC_Samples\x18\x0f \x01(\x05\x12\x19\n\nIS_KnockIn\x18\x10 \x01(\x08:\x05\x66\x61lse\x12\x0f\n\x07\x42\x61rrier\x18\x11 \x01(\x01\x12\x37\n\x0c\x42\x61rrier_Type\x18\x12 \x01(\x0e\x32!.Proto.DevPricing.EnumBarrierType\"\x96\x01\n\x12ProtoDevPricingRsp\x12/\n\x08\x44\x65v_Type\x18\x01 \x02(\x0e\x32\x1d.Proto.DevPricing.EnumDevType\x12\r\n\x05Value\x18\x02 \x02(\x01\x12\x11\n\tValue_Max\x18\x03 \x01(\x01\x12\x11\n\tValue_Min\x18\x04 \x01(\x01\x12\x1a\n\x12\x41vg_Knockout_Month\x18\x05 \x01(\x01*R\n\x0b\x45numDevType\x12\x0b\n\x07Vanilla\x10\x00\x12\x0c\n\x08Sharkfin\x10\x01\x12\r\n\tSharkfin2\x10\x02\x12\x0b\n\x07\x42\x61rrier\x10\x03\x12\x0c\n\x08SnowBall\x10\n*Y\n\x0f\x45numBarrierType\x12\x07\n\x03\x43UO\x10\x00\x12\x07\n\x03\x43UI\x10\x01\x12\x07\n\x03\x43\x44O\x10\x02\x12\x07\n\x03\x43\x44I\x10\x03\x12\x07\n\x03PUO\x10\x04\x12\x07\n\x03PUI\x10\x05\x12\x07\n\x03PDO\x10\x06\x12\x07\n\x03PDI\x10\x07\x42#\n\x0f\x63om.cc.protobufB\x10ProtoDevPricings'
)

_ENUMDEVTYPE = _descriptor.EnumDescriptor(
  name='EnumDevType',
  full_name='Proto.DevPricing.EnumDevType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Vanilla', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Sharkfin', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Sharkfin2', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Barrier', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SnowBall', index=4, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=658,
  serialized_end=740,
)
_sym_db.RegisterEnumDescriptor(_ENUMDEVTYPE)

EnumDevType = enum_type_wrapper.EnumTypeWrapper(_ENUMDEVTYPE)
_ENUMBARRIERTYPE = _descriptor.EnumDescriptor(
  name='EnumBarrierType',
  full_name='Proto.DevPricing.EnumBarrierType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CUO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CUI', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CDO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CDI', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUO', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUI', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PDO', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PDI', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=742,
  serialized_end=831,
)
_sym_db.RegisterEnumDescriptor(_ENUMBARRIERTYPE)

EnumBarrierType = enum_type_wrapper.EnumTypeWrapper(_ENUMBARRIERTYPE)
Vanilla = 0
Sharkfin = 1
Sharkfin2 = 2
Barrier = 3
SnowBall = 10
CUO = 0
CUI = 1
CDO = 2
CDI = 3
PUO = 4
PUI = 5
PDO = 6
PDI = 7



_PROTODEVPRICINGREQ = _descriptor.Descriptor(
  name='ProtoDevPricingReq',
  full_name='Proto.DevPricing.ProtoDevPricingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Dev_Type', full_name='Proto.DevPricing.ProtoDevPricingReq.Dev_Type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Year_Days', full_name='Proto.DevPricing.ProtoDevPricingReq.Year_Days', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=252,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='Proto.DevPricing.ProtoDevPricingReq.Duration', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Volatility', full_name='Proto.DevPricing.ProtoDevPricingReq.Volatility', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RiskFree_Rate', full_name='Proto.DevPricing.ProtoDevPricingReq.RiskFree_Rate', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Strike', full_name='Proto.DevPricing.ProtoDevPricingReq.Strike', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='S0', full_name='Proto.DevPricing.ProtoDevPricingReq.S0', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='S1', full_name='Proto.DevPricing.ProtoDevPricingReq.S1', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Expected_Ret', full_name='Proto.DevPricing.ProtoDevPricingReq.Expected_Ret', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='KnockOut_Ratio', full_name='Proto.DevPricing.ProtoDevPricingReq.KnockOut_Ratio', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='KnockOut_Ratio2', full_name='Proto.DevPricing.ProtoDevPricingReq.KnockOut_Ratio2', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='KnockIn_Ratio', full_name='Proto.DevPricing.ProtoDevPricingReq.KnockIn_Ratio', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='KnockOut_Return', full_name='Proto.DevPricing.ProtoDevPricingReq.KnockOut_Return', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Start_Obsv_Date', full_name='Proto.DevPricing.ProtoDevPricingReq.Start_Obsv_Date', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MC_Samples', full_name='Proto.DevPricing.ProtoDevPricingReq.MC_Samples', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IS_KnockIn', full_name='Proto.DevPricing.ProtoDevPricingReq.IS_KnockIn', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Barrier', full_name='Proto.DevPricing.ProtoDevPricingReq.Barrier', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Barrier_Type', full_name='Proto.DevPricing.ProtoDevPricingReq.Barrier_Type', index=17,
      number=18, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=503,
)


_PROTODEVPRICINGRSP = _descriptor.Descriptor(
  name='ProtoDevPricingRsp',
  full_name='Proto.DevPricing.ProtoDevPricingRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Dev_Type', full_name='Proto.DevPricing.ProtoDevPricingRsp.Dev_Type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Value', full_name='Proto.DevPricing.ProtoDevPricingRsp.Value', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Value_Max', full_name='Proto.DevPricing.ProtoDevPricingRsp.Value_Max', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Value_Min', full_name='Proto.DevPricing.ProtoDevPricingRsp.Value_Min', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Avg_Knockout_Month', full_name='Proto.DevPricing.ProtoDevPricingRsp.Avg_Knockout_Month', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=656,
)

_PROTODEVPRICINGREQ.fields_by_name['Dev_Type'].enum_type = _ENUMDEVTYPE
_PROTODEVPRICINGREQ.fields_by_name['Barrier_Type'].enum_type = _ENUMBARRIERTYPE
_PROTODEVPRICINGRSP.fields_by_name['Dev_Type'].enum_type = _ENUMDEVTYPE
DESCRIPTOR.message_types_by_name['ProtoDevPricingReq'] = _PROTODEVPRICINGREQ
DESCRIPTOR.message_types_by_name['ProtoDevPricingRsp'] = _PROTODEVPRICINGRSP
DESCRIPTOR.enum_types_by_name['EnumDevType'] = _ENUMDEVTYPE
DESCRIPTOR.enum_types_by_name['EnumBarrierType'] = _ENUMBARRIERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoDevPricingReq = _reflection.GeneratedProtocolMessageType('ProtoDevPricingReq', (_message.Message,), {
  'DESCRIPTOR' : _PROTODEVPRICINGREQ,
  '__module__' : 'ProtoDevPricing_pb2'
  # @@protoc_insertion_point(class_scope:Proto.DevPricing.ProtoDevPricingReq)
  })
_sym_db.RegisterMessage(ProtoDevPricingReq)

ProtoDevPricingRsp = _reflection.GeneratedProtocolMessageType('ProtoDevPricingRsp', (_message.Message,), {
  'DESCRIPTOR' : _PROTODEVPRICINGRSP,
  '__module__' : 'ProtoDevPricing_pb2'
  # @@protoc_insertion_point(class_scope:Proto.DevPricing.ProtoDevPricingRsp)
  })
_sym_db.RegisterMessage(ProtoDevPricingRsp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
