// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PackageHead.proto

package com.cc.protobuf;

public final class PackageHeads {
  private PackageHeads() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackageHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Proto.Package.PackageHead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *包类型, 请求/响应
     * </pre>
     *
     * <code>required .Proto.Package.PackageType packageType = 1;</code>
     * @return Whether the packageType field is set.
     */
    boolean hasPackageType();
    /**
     * <pre>
     *包类型, 请求/响应
     * </pre>
     *
     * <code>required .Proto.Package.PackageType packageType = 1;</code>
     * @return The packageType.
     */
    com.cc.protobuf.PackageHeadEnums.PackageType getPackageType();

    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>required .Proto.Package.FunctionCode functionCode = 2;</code>
     * @return Whether the functionCode field is set.
     */
    boolean hasFunctionCode();
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>required .Proto.Package.FunctionCode functionCode = 2;</code>
     * @return The functionCode.
     */
    com.cc.protobuf.PackageHeadEnums.FunctionCode getFunctionCode();

    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>optional string destination = 3;</code>
     * @return Whether the destination field is set.
     */
    boolean hasDestination();
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>optional string destination = 3;</code>
     * @return The destination.
     */
    java.lang.String getDestination();
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>optional string destination = 3;</code>
     * @return The bytes for destination.
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    /**
     * <pre>
     *用户号，对于服务器，可填服务器的标识
     * </pre>
     *
     * <code>optional string userId = 4;</code>
     * @return Whether the userId field is set.
     */
    boolean hasUserId();
    /**
     * <pre>
     *用户号，对于服务器，可填服务器的标识
     * </pre>
     *
     * <code>optional string userId = 4;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <pre>
     *用户号，对于服务器，可填服务器的标识
     * </pre>
     *
     * <code>optional string userId = 4;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     *模块号
     * </pre>
     *
     * <code>optional string moduleId = 5;</code>
     * @return Whether the moduleId field is set.
     */
    boolean hasModuleId();
    /**
     * <pre>
     *模块号
     * </pre>
     *
     * <code>optional string moduleId = 5;</code>
     * @return The moduleId.
     */
    java.lang.String getModuleId();
    /**
     * <pre>
     *模块号
     * </pre>
     *
     * <code>optional string moduleId = 5;</code>
     * @return The bytes for moduleId.
     */
    com.google.protobuf.ByteString
        getModuleIdBytes();

    /**
     * <pre>
     *消息代码
     * </pre>
     *
     * <code>optional int32 messageCode = 6;</code>
     * @return Whether the messageCode field is set.
     */
    boolean hasMessageCode();
    /**
     * <pre>
     *消息代码
     * </pre>
     *
     * <code>optional int32 messageCode = 6;</code>
     * @return The messageCode.
     */
    int getMessageCode();

    /**
     * <pre>
     *消息文字
     * </pre>
     *
     * <code>optional string messageText = 7;</code>
     * @return Whether the messageText field is set.
     */
    boolean hasMessageText();
    /**
     * <pre>
     *消息文字
     * </pre>
     *
     * <code>optional string messageText = 7;</code>
     * @return The messageText.
     */
    java.lang.String getMessageText();
    /**
     * <pre>
     *消息文字
     * </pre>
     *
     * <code>optional string messageText = 7;</code>
     * @return The bytes for messageText.
     */
    com.google.protobuf.ByteString
        getMessageTextBytes();

    /**
     * <pre>
     *自定义文本, 应用层根据需要自行定义作用
     * </pre>
     *
     * <code>optional string customText = 8;</code>
     * @return Whether the customText field is set.
     */
    boolean hasCustomText();
    /**
     * <pre>
     *自定义文本, 应用层根据需要自行定义作用
     * </pre>
     *
     * <code>optional string customText = 8;</code>
     * @return The customText.
     */
    java.lang.String getCustomText();
    /**
     * <pre>
     *自定义文本, 应用层根据需要自行定义作用
     * </pre>
     *
     * <code>optional string customText = 8;</code>
     * @return The bytes for customText.
     */
    com.google.protobuf.ByteString
        getCustomTextBytes();
  }
  /**
   * Protobuf type {@code Proto.Package.PackageHead}
   */
  public static final class PackageHead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Proto.Package.PackageHead)
      PackageHeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PackageHead.newBuilder() to construct.
    private PackageHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageHead() {
      packageType_ = 1;
      functionCode_ = 1;
      destination_ = "";
      userId_ = "";
      moduleId_ = "";
      messageText_ = "";
      customText_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PackageHead();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PackageHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.cc.protobuf.PackageHeadEnums.PackageType value = com.cc.protobuf.PackageHeadEnums.PackageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                packageType_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.cc.protobuf.PackageHeadEnums.FunctionCode value = com.cc.protobuf.PackageHeadEnums.FunctionCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                functionCode_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              destination_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              userId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              moduleId_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              messageCode_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              messageText_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              customText_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cc.protobuf.PackageHeads.internal_static_Proto_Package_PackageHead_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cc.protobuf.PackageHeads.internal_static_Proto_Package_PackageHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cc.protobuf.PackageHeads.PackageHead.class, com.cc.protobuf.PackageHeads.PackageHead.Builder.class);
    }

    private int bitField0_;
    public static final int PACKAGETYPE_FIELD_NUMBER = 1;
    private int packageType_;
    /**
     * <pre>
     *包类型, 请求/响应
     * </pre>
     *
     * <code>required .Proto.Package.PackageType packageType = 1;</code>
     * @return Whether the packageType field is set.
     */
    @java.lang.Override public boolean hasPackageType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *包类型, 请求/响应
     * </pre>
     *
     * <code>required .Proto.Package.PackageType packageType = 1;</code>
     * @return The packageType.
     */
    @java.lang.Override public com.cc.protobuf.PackageHeadEnums.PackageType getPackageType() {
      @SuppressWarnings("deprecation")
      com.cc.protobuf.PackageHeadEnums.PackageType result = com.cc.protobuf.PackageHeadEnums.PackageType.valueOf(packageType_);
      return result == null ? com.cc.protobuf.PackageHeadEnums.PackageType.Request : result;
    }

    public static final int FUNCTIONCODE_FIELD_NUMBER = 2;
    private int functionCode_;
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>required .Proto.Package.FunctionCode functionCode = 2;</code>
     * @return Whether the functionCode field is set.
     */
    @java.lang.Override public boolean hasFunctionCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *功能号
     * </pre>
     *
     * <code>required .Proto.Package.FunctionCode functionCode = 2;</code>
     * @return The functionCode.
     */
    @java.lang.Override public com.cc.protobuf.PackageHeadEnums.FunctionCode getFunctionCode() {
      @SuppressWarnings("deprecation")
      com.cc.protobuf.PackageHeadEnums.FunctionCode result = com.cc.protobuf.PackageHeadEnums.FunctionCode.valueOf(functionCode_);
      return result == null ? com.cc.protobuf.PackageHeadEnums.FunctionCode.PlaceOrder : result;
    }

    public static final int DESTINATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object destination_;
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>optional string destination = 3;</code>
     * @return Whether the destination field is set.
     */
    @java.lang.Override
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>optional string destination = 3;</code>
     * @return The destination.
     */
    @java.lang.Override
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destination_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *目的地
     * </pre>
     *
     * <code>optional string destination = 3;</code>
     * @return The bytes for destination.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private volatile java.lang.Object userId_;
    /**
     * <pre>
     *用户号，对于服务器，可填服务器的标识
     * </pre>
     *
     * <code>optional string userId = 4;</code>
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *用户号，对于服务器，可填服务器的标识
     * </pre>
     *
     * <code>optional string userId = 4;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *用户号，对于服务器，可填服务器的标识
     * </pre>
     *
     * <code>optional string userId = 4;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODULEID_FIELD_NUMBER = 5;
    private volatile java.lang.Object moduleId_;
    /**
     * <pre>
     *模块号
     * </pre>
     *
     * <code>optional string moduleId = 5;</code>
     * @return Whether the moduleId field is set.
     */
    @java.lang.Override
    public boolean hasModuleId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *模块号
     * </pre>
     *
     * <code>optional string moduleId = 5;</code>
     * @return The moduleId.
     */
    @java.lang.Override
    public java.lang.String getModuleId() {
      java.lang.Object ref = moduleId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          moduleId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *模块号
     * </pre>
     *
     * <code>optional string moduleId = 5;</code>
     * @return The bytes for moduleId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModuleIdBytes() {
      java.lang.Object ref = moduleId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moduleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGECODE_FIELD_NUMBER = 6;
    private int messageCode_;
    /**
     * <pre>
     *消息代码
     * </pre>
     *
     * <code>optional int32 messageCode = 6;</code>
     * @return Whether the messageCode field is set.
     */
    @java.lang.Override
    public boolean hasMessageCode() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *消息代码
     * </pre>
     *
     * <code>optional int32 messageCode = 6;</code>
     * @return The messageCode.
     */
    @java.lang.Override
    public int getMessageCode() {
      return messageCode_;
    }

    public static final int MESSAGETEXT_FIELD_NUMBER = 7;
    private volatile java.lang.Object messageText_;
    /**
     * <pre>
     *消息文字
     * </pre>
     *
     * <code>optional string messageText = 7;</code>
     * @return Whether the messageText field is set.
     */
    @java.lang.Override
    public boolean hasMessageText() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *消息文字
     * </pre>
     *
     * <code>optional string messageText = 7;</code>
     * @return The messageText.
     */
    @java.lang.Override
    public java.lang.String getMessageText() {
      java.lang.Object ref = messageText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageText_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息文字
     * </pre>
     *
     * <code>optional string messageText = 7;</code>
     * @return The bytes for messageText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageTextBytes() {
      java.lang.Object ref = messageText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMTEXT_FIELD_NUMBER = 8;
    private volatile java.lang.Object customText_;
    /**
     * <pre>
     *自定义文本, 应用层根据需要自行定义作用
     * </pre>
     *
     * <code>optional string customText = 8;</code>
     * @return Whether the customText field is set.
     */
    @java.lang.Override
    public boolean hasCustomText() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     *自定义文本, 应用层根据需要自行定义作用
     * </pre>
     *
     * <code>optional string customText = 8;</code>
     * @return The customText.
     */
    @java.lang.Override
    public java.lang.String getCustomText() {
      java.lang.Object ref = customText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customText_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *自定义文本, 应用层根据需要自行定义作用
     * </pre>
     *
     * <code>optional string customText = 8;</code>
     * @return The bytes for customText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomTextBytes() {
      java.lang.Object ref = customText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFunctionCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, packageType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, functionCode_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destination_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, moduleId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, messageCode_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, messageText_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, customText_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, packageType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, functionCode_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destination_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, moduleId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, messageCode_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, messageText_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, customText_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cc.protobuf.PackageHeads.PackageHead)) {
        return super.equals(obj);
      }
      com.cc.protobuf.PackageHeads.PackageHead other = (com.cc.protobuf.PackageHeads.PackageHead) obj;

      if (hasPackageType() != other.hasPackageType()) return false;
      if (hasPackageType()) {
        if (packageType_ != other.packageType_) return false;
      }
      if (hasFunctionCode() != other.hasFunctionCode()) return false;
      if (hasFunctionCode()) {
        if (functionCode_ != other.functionCode_) return false;
      }
      if (hasDestination() != other.hasDestination()) return false;
      if (hasDestination()) {
        if (!getDestination()
            .equals(other.getDestination())) return false;
      }
      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (!getUserId()
            .equals(other.getUserId())) return false;
      }
      if (hasModuleId() != other.hasModuleId()) return false;
      if (hasModuleId()) {
        if (!getModuleId()
            .equals(other.getModuleId())) return false;
      }
      if (hasMessageCode() != other.hasMessageCode()) return false;
      if (hasMessageCode()) {
        if (getMessageCode()
            != other.getMessageCode()) return false;
      }
      if (hasMessageText() != other.hasMessageText()) return false;
      if (hasMessageText()) {
        if (!getMessageText()
            .equals(other.getMessageText())) return false;
      }
      if (hasCustomText() != other.hasCustomText()) return false;
      if (hasCustomText()) {
        if (!getCustomText()
            .equals(other.getCustomText())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPackageType()) {
        hash = (37 * hash) + PACKAGETYPE_FIELD_NUMBER;
        hash = (53 * hash) + packageType_;
      }
      if (hasFunctionCode()) {
        hash = (37 * hash) + FUNCTIONCODE_FIELD_NUMBER;
        hash = (53 * hash) + functionCode_;
      }
      if (hasDestination()) {
        hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
        hash = (53 * hash) + getDestination().hashCode();
      }
      if (hasUserId()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId().hashCode();
      }
      if (hasModuleId()) {
        hash = (37 * hash) + MODULEID_FIELD_NUMBER;
        hash = (53 * hash) + getModuleId().hashCode();
      }
      if (hasMessageCode()) {
        hash = (37 * hash) + MESSAGECODE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageCode();
      }
      if (hasMessageText()) {
        hash = (37 * hash) + MESSAGETEXT_FIELD_NUMBER;
        hash = (53 * hash) + getMessageText().hashCode();
      }
      if (hasCustomText()) {
        hash = (37 * hash) + CUSTOMTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getCustomText().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cc.protobuf.PackageHeads.PackageHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cc.protobuf.PackageHeads.PackageHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Proto.Package.PackageHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Proto.Package.PackageHead)
        com.cc.protobuf.PackageHeads.PackageHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cc.protobuf.PackageHeads.internal_static_Proto_Package_PackageHead_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cc.protobuf.PackageHeads.internal_static_Proto_Package_PackageHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cc.protobuf.PackageHeads.PackageHead.class, com.cc.protobuf.PackageHeads.PackageHead.Builder.class);
      }

      // Construct using com.cc.protobuf.PackageHeads.PackageHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packageType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        functionCode_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        destination_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        moduleId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        messageCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        messageText_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        customText_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cc.protobuf.PackageHeads.internal_static_Proto_Package_PackageHead_descriptor;
      }

      @java.lang.Override
      public com.cc.protobuf.PackageHeads.PackageHead getDefaultInstanceForType() {
        return com.cc.protobuf.PackageHeads.PackageHead.getDefaultInstance();
      }

      @java.lang.Override
      public com.cc.protobuf.PackageHeads.PackageHead build() {
        com.cc.protobuf.PackageHeads.PackageHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cc.protobuf.PackageHeads.PackageHead buildPartial() {
        com.cc.protobuf.PackageHeads.PackageHead result = new com.cc.protobuf.PackageHeads.PackageHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packageType_ = packageType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.functionCode_ = functionCode_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.moduleId_ = moduleId_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.messageCode_ = messageCode_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.messageText_ = messageText_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.customText_ = customText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cc.protobuf.PackageHeads.PackageHead) {
          return mergeFrom((com.cc.protobuf.PackageHeads.PackageHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cc.protobuf.PackageHeads.PackageHead other) {
        if (other == com.cc.protobuf.PackageHeads.PackageHead.getDefaultInstance()) return this;
        if (other.hasPackageType()) {
          setPackageType(other.getPackageType());
        }
        if (other.hasFunctionCode()) {
          setFunctionCode(other.getFunctionCode());
        }
        if (other.hasDestination()) {
          bitField0_ |= 0x00000004;
          destination_ = other.destination_;
          onChanged();
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000008;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasModuleId()) {
          bitField0_ |= 0x00000010;
          moduleId_ = other.moduleId_;
          onChanged();
        }
        if (other.hasMessageCode()) {
          setMessageCode(other.getMessageCode());
        }
        if (other.hasMessageText()) {
          bitField0_ |= 0x00000040;
          messageText_ = other.messageText_;
          onChanged();
        }
        if (other.hasCustomText()) {
          bitField0_ |= 0x00000080;
          customText_ = other.customText_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPackageType()) {
          return false;
        }
        if (!hasFunctionCode()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cc.protobuf.PackageHeads.PackageHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cc.protobuf.PackageHeads.PackageHead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int packageType_ = 1;
      /**
       * <pre>
       *包类型, 请求/响应
       * </pre>
       *
       * <code>required .Proto.Package.PackageType packageType = 1;</code>
       * @return Whether the packageType field is set.
       */
      @java.lang.Override public boolean hasPackageType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *包类型, 请求/响应
       * </pre>
       *
       * <code>required .Proto.Package.PackageType packageType = 1;</code>
       * @return The packageType.
       */
      @java.lang.Override
      public com.cc.protobuf.PackageHeadEnums.PackageType getPackageType() {
        @SuppressWarnings("deprecation")
        com.cc.protobuf.PackageHeadEnums.PackageType result = com.cc.protobuf.PackageHeadEnums.PackageType.valueOf(packageType_);
        return result == null ? com.cc.protobuf.PackageHeadEnums.PackageType.Request : result;
      }
      /**
       * <pre>
       *包类型, 请求/响应
       * </pre>
       *
       * <code>required .Proto.Package.PackageType packageType = 1;</code>
       * @param value The packageType to set.
       * @return This builder for chaining.
       */
      public Builder setPackageType(com.cc.protobuf.PackageHeadEnums.PackageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        packageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *包类型, 请求/响应
       * </pre>
       *
       * <code>required .Proto.Package.PackageType packageType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageType_ = 1;
        onChanged();
        return this;
      }

      private int functionCode_ = 1;
      /**
       * <pre>
       *功能号
       * </pre>
       *
       * <code>required .Proto.Package.FunctionCode functionCode = 2;</code>
       * @return Whether the functionCode field is set.
       */
      @java.lang.Override public boolean hasFunctionCode() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *功能号
       * </pre>
       *
       * <code>required .Proto.Package.FunctionCode functionCode = 2;</code>
       * @return The functionCode.
       */
      @java.lang.Override
      public com.cc.protobuf.PackageHeadEnums.FunctionCode getFunctionCode() {
        @SuppressWarnings("deprecation")
        com.cc.protobuf.PackageHeadEnums.FunctionCode result = com.cc.protobuf.PackageHeadEnums.FunctionCode.valueOf(functionCode_);
        return result == null ? com.cc.protobuf.PackageHeadEnums.FunctionCode.PlaceOrder : result;
      }
      /**
       * <pre>
       *功能号
       * </pre>
       *
       * <code>required .Proto.Package.FunctionCode functionCode = 2;</code>
       * @param value The functionCode to set.
       * @return This builder for chaining.
       */
      public Builder setFunctionCode(com.cc.protobuf.PackageHeadEnums.FunctionCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        functionCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *功能号
       * </pre>
       *
       * <code>required .Proto.Package.FunctionCode functionCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFunctionCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        functionCode_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object destination_ = "";
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>optional string destination = 3;</code>
       * @return Whether the destination field is set.
       */
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>optional string destination = 3;</code>
       * @return The destination.
       */
      public java.lang.String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destination_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>optional string destination = 3;</code>
       * @return The bytes for destination.
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>optional string destination = 3;</code>
       * @param value The destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestination(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>optional string destination = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的地
       * </pre>
       *
       * <code>optional string destination = 3;</code>
       * @param value The bytes for destination to set.
       * @return This builder for chaining.
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <pre>
       *用户号，对于服务器，可填服务器的标识
       * </pre>
       *
       * <code>optional string userId = 4;</code>
       * @return Whether the userId field is set.
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *用户号，对于服务器，可填服务器的标识
       * </pre>
       *
       * <code>optional string userId = 4;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户号，对于服务器，可填服务器的标识
       * </pre>
       *
       * <code>optional string userId = 4;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户号，对于服务器，可填服务器的标识
       * </pre>
       *
       * <code>optional string userId = 4;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户号，对于服务器，可填服务器的标识
       * </pre>
       *
       * <code>optional string userId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户号，对于服务器，可填服务器的标识
       * </pre>
       *
       * <code>optional string userId = 4;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object moduleId_ = "";
      /**
       * <pre>
       *模块号
       * </pre>
       *
       * <code>optional string moduleId = 5;</code>
       * @return Whether the moduleId field is set.
       */
      public boolean hasModuleId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *模块号
       * </pre>
       *
       * <code>optional string moduleId = 5;</code>
       * @return The moduleId.
       */
      public java.lang.String getModuleId() {
        java.lang.Object ref = moduleId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            moduleId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *模块号
       * </pre>
       *
       * <code>optional string moduleId = 5;</code>
       * @return The bytes for moduleId.
       */
      public com.google.protobuf.ByteString
          getModuleIdBytes() {
        java.lang.Object ref = moduleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          moduleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *模块号
       * </pre>
       *
       * <code>optional string moduleId = 5;</code>
       * @param value The moduleId to set.
       * @return This builder for chaining.
       */
      public Builder setModuleId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        moduleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *模块号
       * </pre>
       *
       * <code>optional string moduleId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearModuleId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        moduleId_ = getDefaultInstance().getModuleId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *模块号
       * </pre>
       *
       * <code>optional string moduleId = 5;</code>
       * @param value The bytes for moduleId to set.
       * @return This builder for chaining.
       */
      public Builder setModuleIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        moduleId_ = value;
        onChanged();
        return this;
      }

      private int messageCode_ ;
      /**
       * <pre>
       *消息代码
       * </pre>
       *
       * <code>optional int32 messageCode = 6;</code>
       * @return Whether the messageCode field is set.
       */
      @java.lang.Override
      public boolean hasMessageCode() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *消息代码
       * </pre>
       *
       * <code>optional int32 messageCode = 6;</code>
       * @return The messageCode.
       */
      @java.lang.Override
      public int getMessageCode() {
        return messageCode_;
      }
      /**
       * <pre>
       *消息代码
       * </pre>
       *
       * <code>optional int32 messageCode = 6;</code>
       * @param value The messageCode to set.
       * @return This builder for chaining.
       */
      public Builder setMessageCode(int value) {
        bitField0_ |= 0x00000020;
        messageCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息代码
       * </pre>
       *
       * <code>optional int32 messageCode = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        messageCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object messageText_ = "";
      /**
       * <pre>
       *消息文字
       * </pre>
       *
       * <code>optional string messageText = 7;</code>
       * @return Whether the messageText field is set.
       */
      public boolean hasMessageText() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *消息文字
       * </pre>
       *
       * <code>optional string messageText = 7;</code>
       * @return The messageText.
       */
      public java.lang.String getMessageText() {
        java.lang.Object ref = messageText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息文字
       * </pre>
       *
       * <code>optional string messageText = 7;</code>
       * @return The bytes for messageText.
       */
      public com.google.protobuf.ByteString
          getMessageTextBytes() {
        java.lang.Object ref = messageText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息文字
       * </pre>
       *
       * <code>optional string messageText = 7;</code>
       * @param value The messageText to set.
       * @return This builder for chaining.
       */
      public Builder setMessageText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        messageText_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息文字
       * </pre>
       *
       * <code>optional string messageText = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageText() {
        bitField0_ = (bitField0_ & ~0x00000040);
        messageText_ = getDefaultInstance().getMessageText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息文字
       * </pre>
       *
       * <code>optional string messageText = 7;</code>
       * @param value The bytes for messageText to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        messageText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customText_ = "";
      /**
       * <pre>
       *自定义文本, 应用层根据需要自行定义作用
       * </pre>
       *
       * <code>optional string customText = 8;</code>
       * @return Whether the customText field is set.
       */
      public boolean hasCustomText() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       *自定义文本, 应用层根据需要自行定义作用
       * </pre>
       *
       * <code>optional string customText = 8;</code>
       * @return The customText.
       */
      public java.lang.String getCustomText() {
        java.lang.Object ref = customText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            customText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *自定义文本, 应用层根据需要自行定义作用
       * </pre>
       *
       * <code>optional string customText = 8;</code>
       * @return The bytes for customText.
       */
      public com.google.protobuf.ByteString
          getCustomTextBytes() {
        java.lang.Object ref = customText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *自定义文本, 应用层根据需要自行定义作用
       * </pre>
       *
       * <code>optional string customText = 8;</code>
       * @param value The customText to set.
       * @return This builder for chaining.
       */
      public Builder setCustomText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        customText_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自定义文本, 应用层根据需要自行定义作用
       * </pre>
       *
       * <code>optional string customText = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomText() {
        bitField0_ = (bitField0_ & ~0x00000080);
        customText_ = getDefaultInstance().getCustomText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自定义文本, 应用层根据需要自行定义作用
       * </pre>
       *
       * <code>optional string customText = 8;</code>
       * @param value The bytes for customText to set.
       * @return This builder for chaining.
       */
      public Builder setCustomTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        customText_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Proto.Package.PackageHead)
    }

    // @@protoc_insertion_point(class_scope:Proto.Package.PackageHead)
    private static final com.cc.protobuf.PackageHeads.PackageHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cc.protobuf.PackageHeads.PackageHead();
    }

    public static com.cc.protobuf.PackageHeads.PackageHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PackageHead>
        PARSER = new com.google.protobuf.AbstractParser<PackageHead>() {
      @java.lang.Override
      public PackageHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageHead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageHead> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageHead> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cc.protobuf.PackageHeads.PackageHead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_Package_PackageHead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proto_Package_PackageHead_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PackageHead.proto\022\rProto.Package\032\025Pack" +
      "ageHeadEnum.proto\"\346\001\n\013PackageHead\022/\n\013pac" +
      "kageType\030\001 \002(\0162\032.Proto.Package.PackageTy" +
      "pe\0221\n\014functionCode\030\002 \002(\0162\033.Proto.Package" +
      ".FunctionCode\022\023\n\013destination\030\003 \001(\t\022\016\n\006us" +
      "erId\030\004 \001(\t\022\020\n\010moduleId\030\005 \001(\t\022\023\n\013messageC" +
      "ode\030\006 \001(\005\022\023\n\013messageText\030\007 \001(\t\022\022\n\ncustom" +
      "Text\030\010 \001(\tB\037\n\017com.cc.protobufB\014PackageHe" +
      "ads"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cc.protobuf.PackageHeadEnums.getDescriptor(),
        });
    internal_static_Proto_Package_PackageHead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proto_Package_PackageHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proto_Package_PackageHead_descriptor,
        new java.lang.String[] { "PackageType", "FunctionCode", "Destination", "UserId", "ModuleId", "MessageCode", "MessageText", "CustomText", });
    com.cc.protobuf.PackageHeadEnums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
